### ISSUE TITLE
Your project has been added to a list of copyfree works.

### ISSUE THREAD

**Issue by apotheon** [palominolabs/gradle-git-clone-task#11]
http://copyfree.org/resources/works#gradle-git-clone-task

Please let me know if there are any inaccuracies to be corrected or improvements to be made to the listing.

**Comment by marshallpierce** [comment]
Thanks! I have many other copyfree works on [my bitbucket](https://bitbucket.org/marshallpierce/workspace/projects/OSS).

**Comment by apotheon** [comment]
Thanks for the info.  I'll give it a look.

If you wish, you may [open a ticket](https://fossrec.com/u/apotheon/cfworks/index.cgi/tktnew) to list links for the projects you would like to see listed, given some level of readiness for general use and desire for them to be visible.  That'll help fast-track them getting added.
