### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by Cross22** [palominolabs/gradle-git-clone-task#3]
This looks like a nice and easy to use extension for gradle. What are your terms of use?

**Comment by marshallpierce** [comment]
Hey, sorry for the oversight. It's released under the COIL license: http://copyfree.org/content/standard/licenses/coil/license.txt

The short version is: use it however you like with no restrictions. I'll add a LICENSE file when I get a minute.

**Comment by Cross22** [comment]
Much appreciated. Thank you, Marshall!
