### ISSUE TITLE
Port parameter

### ISSUE THREAD

**Issue by lukeisontheroad** [palominolabs/gradle-git-clone-task#4]
Can you please add a parameter to pass a custom port? It won't work if I put the port in the uri.

**Comment by marshallpierce** [comment]
Bummer! Sounds useful; I'll get to it when I can.

**Comment by marshallpierce** [comment]
Ports seem to work ok for me; see tests added in https://github.com/palominolabs/gradle-git-clone-task/commit/ffecd99750c8e4b73df6eaa3f7b93acead83e309. Does that not work for you in your use case?
