### ISSUE TITLE
treeish = 'master' results in "Couldn't resolve <master>", yet an arbitrary hash works

### ISSUE THREAD

**Issue by jzacsh** [palominolabs/gradle-git-clone-task#6]
I'm guessing i'm just doing something wrong, but I suppose its possible no one else has needed this yet.

**Comment by marshallpierce** [comment]
Try it with 'origin/master'; that should work. I've clarified the readme as well. :)

**Comment by jzacsh** [comment]
I thought I did, will give this another try when I'm back at a computer.
Thanks!

**Comment by marshallpierce** [comment]
Closing from inactivity.
