### ISSUE TITLE
 com.jcraft.jsch.JSchException: UnknownHostKey

### ISSUE THREAD

**Issue by tannymanny** [palominolabs/gradle-git-clone-task#8]
I am getting problem using a git repo that needs ssh verification. 

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'org.ajoberstar:gradle-git:1.5.1'
       classpath 'com.palominolabs.gradle.task:gradle-git-clone-task:0.0.2'
    }
}

// use any task name you like
task cloneSomeRepo(type: com.palominolabs.gradle.task.git.clone.GitCloneTask) {
    dir = file("../library")
    uri = 'git@domain.com:8085/path/repo.git'
    treeish = 'master' 
}

```

The error that i get from gradle is :  
- What went wrong:
  Execution failed for task ':cloneSomeRepo'.
  > com.jcraft.jsch.JSchException: UnknownHostKey: domain.com. RSA key fingerprint is 33:c0:e2:98:93:d2:a4:43:ec:98:60:5b:cd:ad:3b:b8

This specific key fingerprint in the error, i don't have it defined in either the "known_hosts" file or in the id_rsa files. SO i don;t know where it is picking up that key from.

**Comment by marshallpierce** [comment]
It sounds like it's an error because it's *not* in the known_hosts file. If you add it to known_hosts (e.g. by ssh'ing manually), does it work?

**Comment by swavkulinski** [comment]
I have same issue however git itself works fine and known_hosts has the entry.

**Comment by marshallpierce** [comment]
Is it perhaps a typo in the domain that's preventing DNS resolution?

**Comment by marshallpierce** [comment]
Idle.
