### ISSUE TITLE
Clone checkout/fetch broken

### ISSUE THREAD

**Issue by ecobos** [palominolabs/gradle-git-clone-task#9]
If the clone directory already exists and its remote changes, calling the task again does not update the cloned directory as is specified to be the case in the README file. In other words, checkout and fetch does not retrieve the most current version. Nothing in the local clone directory changes. No errors displayed.

**Comment by marshallpierce** [comment]
Thanks for the bug report. Do you happen to have a test case that reproduces this?

**Comment by marshallpierce** [comment]
Is the issue that you're specifying a branch name as the treeish, and it's not doing a fetch when it already can resolve the branch name to an existing commit (from a previous run of the task)?

**Comment by marshallpierce** [comment]
I've added a `forceFetch` option in 0.0.3. Feel free to re-open if that doesn't solve your issue.
